# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html

parameters:
    pdo.db_options:
        db_table:    sessions
        db_id_col:   sess_id
        db_data_col: sess_data
        db_time_col: sess_time
        db_lifetime_col: sess_lifetime

services:
    pdo:
        class: PDO
        arguments:
            - 'mysql:host=%database_host%;dbname=%database_name%'
            - '%database_user%'
            - '%database_password%'
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ['@pdo','%pdo.db_options%']


    gos_web_socket.client_storage.driver.predis:
        class: Gos\Bundle\WebSocketBundle\Client\Driver\PredisDriver
        arguments:
            - @snc_redis.client_storage.driver
            - %web_socket_server.client_storage.prefix% #(optionally)if you use prefi